[versions]
jersey = "3.1.1"
junit = "5.9.2"
log4j2 = "2.25.3"
prometheus = "0.16.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.3.0" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
vpdb-gradle = { id = "org.veupathdb.lib.gradle.container.container-utils", version = "6.4.2" }


[libraries]
vpdb-hashId = { module = "org.veupathdb.lib:hash-id", version = "1.0.2" }
vpdb-containerCore = { module = "org.veupathdb.lib:jaxrs-container-core", version = "7.1.4" }
vpdb-fgpUtil-db = { module = "org.gusdb:fgputil-db", version = "3.1.0-jakarta" }
vpdb-blast = { module = "org.veupathdb.lib:java-blast", version = "5.0.9" }
vpdb-diamond = { module = "org.veupathdb.lib:diamondcli", version = "0.5.19" }
vpdb-metrics = { module = "org.veupathdb.lib:lib-prometheus-stats", version = "1.1.0" }
vpdb-fireworq = { module = "org.veupathdb.lib:jvm-fireworq", version = "1.0.4" }

jersey-grizzly-http = { module = "org.glassfish.jersey.containers:jersey-container-grizzly2-http", version.ref = "jersey" }
jersey-grizzly-servlet = { module = "org.glassfish.jersey.containers:jersey-container-grizzly2-servlet", version.ref = "jersey" }
jersey-media-jackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson", version.ref = "jersey" }
jersey-media-multipart = { module = "org.glassfish.jersey.media:jersey-media-multipart", version.ref = "jersey" }

jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2", version = "4.0.1" }

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }

jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version = "2.17.2" }

prometheus-client = { module = "io.prometheus:simpleclient", version.ref = "prometheus" }
prometheus-common = { module = "io.prometheus:simpleclient_common", version.ref = "prometheus" }

fxcpds-sql-import = { module = "io.vulpine.lib:sql-import", version = "0.2.1" }
fxcpds-sql-utils = { module = "io.vulpine.lib:lib-query-util", version = "2.1.0" }
fxcpds-checkedLambas = { module = "io.vulpine.lib:Jackfish", version = "1.1.0" }
fxcpds-either = { module = "io.vulpine.lib:iffy", version = "1.0.1" }

friendlyId = { module = "com.devskiller.friendly-id:friendly-id", version = "1.1.0" }
pico-lib = { module = "info.picocli:picocli", version = "4.7.7" }
pico-generator = { module = "info.picocli:picocli-codegen", version = "4.7.7" }

test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "junit" }
test-junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
test-mockito = { module = "org.mockito:mockito-core", version = "5.2.0" }

test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-junit-compat = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
test-junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.2" }


[bundles]
jersey = [
  "jersey-grizzly-http",
  "jersey-grizzly-servlet",
  "jersey-media-jackson",
  "jersey-media-multipart",
  "jersey-hk2",
]

logging = [ "log4j-api", "log4j-core" ]

metrics = [ "prometheus-client", "prometheus-common" ]

trashLibs = [ "fxcpds-checkedLambas", "fxcpds-either", "fxcpds-sql-import", "fxcpds-sql-utils" ]

testing = [ "test-junit-api", "test-junit-params", "test-mockito" ]